version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
